### ISSUE TITLE
Reading nbits = 1, 2 or 4 in fil_reader.py

### ISSUE THREAD

**Issue by evanocathain** [UCBerkeleySETI/blimpy#152]
**Describe the bug**
It doesn't seem that blimpy's fil_reader.py can read sigproc filterbank files unless they are 8, 16, 32 bits.

I believe it is due to this line:

self._n_bytes = int(self.header['nbits'] / 8)  #number of bytes per digit.

Oddly enough I think without the int cast some downstream issues might work out ok, but it still wouldn't be right. So I suppose this a request that the standard 1, 2 and 4-bit reading methods be added.

**Comment by texadactyl** [comment]
@evanocathain This is covered in issue #151 and PR #146.

**Comment by telegraphic** [comment]
Hmm, we did have basic support for 1/2/4 bits in earlier code, e.g. https://github.com/UCBerkeleySETI/blimpy/blob/b3239931d5cc20fd0137a06752b808b3786022ad/blimpy/deprecated/filterbank.py#L247

There is some [blimpy code already for reading low bitwidth data](https://github.com/UCBerkeleySETI/blimpy/blob/master/blimpy/utils.py#L59), however it seemed to be about twice as slow as sigpyproc (in a poorly controlled test). 

I would, however, quite like to refactor the code to use [numpy.memmap](https://numpy.org/doc/stable/reference/generated/numpy.memmap.html), and have better astropy integration; memmap doesn't support 1/2/4 bits so that's not going to make pulsar folks happy.

One course of action is to port sigpyproc's 1/2/4 bit reading in C using pybind11. Will look into this

**Comment by telegraphic** [comment]
Here's a simple 1/2/4 bit to/from 8 bit numpy array package: https://github.com/telegraphic/numbits

I think this is better as a separate package from blimpy as it does a very specific thing. Integration will take a while as it'll be a bit tricky to make sure strides are right and plotting works (I just wanted to do the fun bit tonight!)

**Comment by texadactyl** [comment]
Agree with last remark from @telegraphic
