### ISSUE TITLE
Blanking DC bin not working properly 

### ISSUE THREAD

**Issue by jeenriquez** [UCBerkeleySETI/blimpy#75]
**Describe the bug**
A bin is being blanked as the DC bin incorrectly. 

**Expected behavior**
The blanking of the DC bin should only happen when the selected data has the exact dimensions as a coarse channel. Otherwise, this should be ignored.

**Comment by david-macmahon** [comment]
Blanking the "DC bin" of each coarse channel can be tricky since the filterbank file header does not indicate how any fine channels there are per coarse channel.  If the filter bank file does not start at the very edge of a coarse channel, computing the DC channel numbers would also need to know the fine channel offset (also not indicated in the filter bank header).  I agree that doing this only for "known cases" (i.e. our standard observing products) and NOT doing it for unknown cases is a good first step.  Is there an option to turn off DC blanking altogether?

**Comment by jeenriquez** [comment]
This feature is only for plotting purposes. There is an option (-D) for turning this on/off.

**Comment by jeenriquez** [comment]
@telegraphic  I found the culprit here. In file_wrapper.py the new way to calculate the number of coarse channels returns and int: ```n_coarse_chan = int(bandwidth / chan_bw)```. Was there a reason to make this change in the code?

**Comment by telegraphic** [comment]
I think `n_coarse_chan` is used as an index, or to derive an index, to an array right? In Py3 this will fail if not an int, and even in Py2 I think treating it as an int makes sense. 

IIRC, the original DC blanking code broke Parkes (44 channels per file!), and my first set of changes for Parkes broke GBT, but I thought this was currently working for both?

The DC blanking is a bit of a pain, ideally we would know from the file metadata how many coarse channels there are -- maybe this should be added to h5 files?

**Comment by texadactyl** [comment]
I believe that @lacker fixed this issue awhile back.
